language: node_js
node_js: node
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: oWG/A8n5J4C4zRKPEdeSLDx6Rvq1MJXe49mNvOjHG2xixVWiNygr1KX1rHN7gn6oGEXprtGLATAzx4nOOrE5xCWznDa+R7jMRGc6FUeGURDlSZnyT6ImPbeMJB+fu4oMx1VmOhYoYghsFI5HMy0v9oCgz0nggqEjb4lG+s39CfXcronMNzVxjF/Cd2Z8Ofme7uphoQWjT+/2NFgnUqMNMcbJ0zl27cPDxPhjRgl0Onm58N0YOJAXCds7FyOYzGM+MpU4K936qqqAD7XhQRuy5WSiRELgAdkuvRb5CnU6ZZXIFYgDGbHEzD0QIjQOSX2piRGjMt2gedjE7TZxuDnp+YCNQAQ1dl7tG2MruA53CVry2al300qB350tvd9Z3+/euQN1nxU8M5QOjNfHn1P4OneL5p4t6py0IrP06qqVx+jNGgxNvWptSgPCWsA6bWXcCOWUmexUCgCAlBhlccR9QgJMH2r3CZsYb0nHSOWFyW323MFXNzhgjWobW7h8F85UL2QXIWJcfF1H4ZSsw5XNpCrm07W4ARubbPl9IJwYOvbPpOG+NRSuYu9KZHrnq5sloXb7NmTniSPuireMVwq4xfb34UhRkZWyTiuihQFe8wOCZTfSatQzlWPq7KPT6gNQk8M+n5x2lvBm1G8MLjJ+/s78RJTIUsqPSvpHAdUI5SM=
  app: secret-hamlet-76574
  on:
    repo: ecarlson1201/blog-api
